[RPS-474] Cleaning up pipeline resources
NHS-digital-website/deploy pull request #18
Opened 2018-04-03 11:39 UTC by wojtek-oledzki

2018-04-06 10:25 UTC, wojtek-oledzki commented on README.md
> +$(make aws-sudo PROFILE=nhsd-profile-name TOKEN=123789)
indicate that "TOKEN" is a AWS MFA token

2018-04-06 10:25 UTC, wojtek-oledzki commented on ansible/vars/dev/environment.yml
>      Project: Publication Service
lets change to Digital Website

2018-04-06 10:25 UTC, wojtek-oledzki commented on ansible/vars/dev/environment.yml
>  aws_ondemand:
rename to ondemand here and in ondemand role `defaults/main.yml`

2018-04-06 10:25 UTC, wojtek-oledzki commented on ansible/vars/mgt/environment.yml
> +    Project: Publication Service
Digital Website

2018-04-06 10:25 UTC, wojtek-oledzki commented on ansible/vars/mgt/environment.yml
> +      vpc_id: vpc-65b45401
comment out with descriptive comment explaining when to use

2018-04-06 10:25 UTC, wojtek-oledzki commented on docs/aws/cd-pipelines.md
> +
more comment

2018-04-11 09:52 UTC, ngta1 requested changes
Looks good.  Just need to squash to 1 commit.

2018-04-11 10:23 UTC, nhs-digital-website-ps-pipeline commented
@ngta1 squashed

2018-04-11 10:24 UTC, ngta1 approved these changes

2018-04-11 10:32 UTC, merged